from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CROSSWALK = ROOT / "manifests" / "table_to_script_crosswalk.csv"
OUT_MD = ROOT / "docs" / "c7_format_delta_explanation.md"
OUT_CSV = ROOT / "docs" / "c7_format_delta_cells.csv"
TOL = 1e-10


def _row() -> dict[str, str]:
    with CROSSWALK.open(newline="") as f:
        for row in csv.DictReader(f):
            if row["table_id"] == "C7":
                return row
    raise RuntimeError("C7 not found in crosswalk")


def _float(value: str) -> float | None:
    try:
        return float(value)
    except ValueError:
        return None


def main() -> int:
    row = _row()
    reference = ROOT / row["capsule_generated_csv"]
    reproduced = ROOT / "outputs" / "paper_exports" / "tables" / Path(row["generated_csv"]).name
    reference_tex = ROOT / row["capsule_generated_tex"]
    reproduced_tex = ROOT / "outputs" / "paper_exports" / "latex" / Path(row["generated_tex"]).name
    if not reproduced.exists():
        raise SystemExit(f"Reproduced C7 CSV is missing: {reproduced}. Run C7/full reproduction first.")

    with reference.open(newline="") as f, reproduced.open(newline="") as g:
        ref_rows = list(csv.reader(f))
        rep_rows = list(csv.reader(g))
    header = ref_rows[0]
    deltas: list[dict[str, str]] = []
    max_abs_delta = 0.0
    non_numeric = 0
    for row_idx, (ref_row, rep_row) in enumerate(zip(ref_rows, rep_rows), start=1):
        for col_idx, (ref_value, rep_value) in enumerate(zip(ref_row, rep_row), start=1):
            if ref_value == rep_value:
                continue
            ref_float = _float(ref_value)
            rep_float = _float(rep_value)
            if ref_float is None or rep_float is None:
                non_numeric += 1
                abs_delta = "NA"
                within = "false"
            else:
                delta = abs(ref_float - rep_float)
                max_abs_delta = max(max_abs_delta, delta)
                abs_delta = f"{delta:.18g}"
                within = "true" if delta <= TOL else "false"
            deltas.append(
                {
                    "row_number": str(row_idx),
                    "column_number": str(col_idx),
                    "column_name": header[col_idx - 1] if row_idx > 1 and col_idx <= len(header) else "header",
                    "reference_value": ref_value,
                    "reproduced_value": rep_value,
                    "absolute_delta": abs_delta,
                    "within_tolerance": within,
                }
            )

    with OUT_CSV.open("w", newline="") as f:
        fields = ["row_number", "column_number", "column_name", "reference_value", "reproduced_value", "absolute_delta", "within_tolerance"]
        writer = csv.DictWriter(f, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(deltas)

    tex_status = "exact_match" if reference_tex.read_bytes() == reproduced_tex.read_bytes() else "content_delta"
    all_within = all(d["within_tolerance"] == "true" for d in deltas)
    lines = [
        "# C7 Format-Only Delta Explanation",
        "",
        "Table C7 is the matched AI-talking comparison sample generated by `test_15_matched_ai_talking_sample`.",
        "",
        "## Verdict",
        "",
        "The C7 CSV difference is a numeric string representation delta, not a numerical content difference.",
        "",
        f"- Differing CSV cells: {len(deltas)}",
        f"- Maximum absolute numeric delta: {max_abs_delta:.18g}",
        f"- Tolerance used by the reproduction gate: {TOL:.0e}",
        f"- All differing cells within tolerance: {'yes' if all_within else 'no'}",
        f"- TeX output status: `{tex_status}`",
        f"- Non-numeric differing cells: {non_numeric}",
        "",
        "The full cell-level audit is stored in `docs/c7_format_delta_cells.csv`.",
        "",
        "## Cell-Level Differences",
        "",
        "| Row | Column | Name | Reference | Reproduced | Abs. delta | Within tolerance |",
        "|---:|---:|---|---:|---:|---:|---|",
    ]
    for item in deltas:
        lines.append(
            "| {row_number} | {column_number} | `{column_name}` | {reference_value} | {reproduced_value} | {absolute_delta} | {within_tolerance} |".format(**item)
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "The differences are at floating-point representation scale, for example changes in the final decimal places such as `...291` versus `...908`. The generated TeX output is byte-identical, so the manuscript-facing table remains stable. Keeping this as `format_only_delta` is preferable to forcing old platform-specific float strings into the publication script.",
        ]
    )
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_MD}")
    print(f"Wrote {OUT_CSV}")
    return 0 if all_within and tex_status == "exact_match" else 1


if __name__ == "__main__":
    raise SystemExit(main())
