from __future__ import annotations

PAGE_SPECS = [
    {
        "group": "Start",
        "key": "home",
        "title": "Home / Project Overview",
        "icon": "🏛️",
        "primary_user": "all users",
        "task": "Understand the paper, workstation, modes, and first actions.",
        "inputs": "paper, data product, and extension manifests",
        "outputs": "project overview, metrics, first commands",
        "safety_rule": "No private data inspection.",
    },
    {
        "group": "Start",
        "key": "portfolio_demo",
        "title": "Portfolio Demo Mode",
        "icon": "✨",
        "primary_user": "portfolio reviewer",
        "task": "See the nonprivate capability showcase.",
        "inputs": "manifests only",
        "outputs": "safe project narrative and capability summary",
        "safety_rule": "Hide private-data-root instructions.",
    },
    {
        "group": "Paper Review",
        "key": "paper_results",
        "title": "Paper Results",
        "icon": "📄",
        "primary_user": "supervisor or research client",
        "task": "Review tables and figures in paper order.",
        "inputs": "paper table workbench",
        "outputs": "paper-section result cards and export commands",
        "safety_rule": "Do not confuse exploratory outputs with frozen evidence.",
    },
    {
        "group": "Paper Review",
        "key": "table_explorer",
        "title": "Table Explorer",
        "icon": "🔎",
        "primary_user": "technical coauthor",
        "task": "Inspect one table or figure deeply.",
        "inputs": "paper table workbench",
        "outputs": "script, command, constructs, outputs, safe modification notes",
        "safety_rule": "Copy commands only; do not execute them from the browser.",
    },
    {
        "group": "Data And Constructs",
        "key": "data_room",
        "title": "Data Room",
        "icon": "🗄️",
        "primary_user": "technical coauthor or data editor",
        "task": "Locate data products and understand private-data boundaries.",
        "inputs": "data product catalog",
        "outputs": "coverage, keys, logical paths, locate-data commands",
        "safety_rule": "Hide private-data-root commands in Demo Mode.",
    },
    {
        "group": "Data And Constructs",
        "key": "construct_audits",
        "title": "Construct Audits",
        "icon": "🧭",
        "primary_user": "coauthor or data editor",
        "task": "Open construct playbooks and validation surfaces.",
        "inputs": "construct playbook registry",
        "outputs": "playbook links and construct-info commands",
        "safety_rule": "No private row examples.",
    },
    {
        "group": "Extensions And Reproduction",
        "key": "extension_lab",
        "title": "Extension Lab",
        "icon": "🧪",
        "primary_user": "technical coauthor",
        "task": "Inspect extension lanes and interpretation limits.",
        "inputs": "extension workbench",
        "outputs": "extension cards, status, commands, limits",
        "safety_rule": "Label extension outputs as exploratory unless promoted.",
    },
    {
        "group": "Extensions And Reproduction",
        "key": "reproduction_status",
        "title": "Reproduction Status",
        "icon": "✅",
        "primary_user": "journal data editor",
        "task": "Verify reproduction and audit posture.",
        "inputs": "status docs and manifests",
        "outputs": "status links and audit commands",
        "safety_rule": "No command execution from the browser.",
    },
    {
        "group": "Extensions And Reproduction",
        "key": "share_export",
        "title": "Share / Export Center",
        "icon": "📦",
        "primary_user": "all users",
        "task": "Find export, setup, dashboard, and share-readiness commands.",
        "inputs": "workbench and dashboard commands",
        "outputs": "copy-ready commands and share checklist pointers",
        "safety_rule": "Commands are displayed only.",
    },
]


def specs_by_key() -> dict[str, dict[str, str]]:
    return {spec["key"]: spec for spec in PAGE_SPECS}
