from __future__ import annotations

PAGE_SPECS = [
    {
        "group": "Start",
        "key": "home",
        "title": "Home / Project Overview",
        "icon": "🏛️",
        "primary_user": "all users",
        "task": "Understand the paper, workstation, modes, and first actions.",
        "inputs": "paper, data product, and extension manifests",
        "outputs": "project overview, metrics, first commands",
        "safety_rule": "No private data inspection.",
    },
    {
        "group": "Start",
        "key": "portfolio_demo",
        "title": "Portfolio Demo Mode",
        "icon": "✨",
        "primary_user": "portfolio reviewer",
        "task": "See the nonprivate capability showcase and reusable methodology.",
        "inputs": "manifests and static portfolio narrative",
        "outputs": "safe case study, workflow, capability summary, and demo boundary",
        "safety_rule": "Hide private-data-root instructions and disable command execution.",
    },
    {
        "group": "Paper Review",
        "key": "paper_results",
        "title": "Paper Results",
        "icon": "📄",
        "primary_user": "supervisor or research client",
        "task": "Review tables and figures in paper order.",
        "inputs": "paper table workbench",
        "outputs": "paper-section result cards and export commands",
        "safety_rule": "Do not confuse exploratory outputs with frozen evidence.",
    },
    {
        "group": "Paper Review",
        "key": "table_explorer",
        "title": "Table Explorer",
        "icon": "🔎",
        "primary_user": "supervisor, research client, or technical coauthor",
        "task": "Review one table by paper label, then inspect implementation details if needed.",
        "inputs": "paper table workbench and repo-contained artifacts",
        "outputs": "Open First panel, safe previews, downloads, script, commands, and safe modification notes",
        "safety_rule": "Preview repo-contained artifacts only; route approved execution to Command Center.",
    },
    {
        "group": "Data And Constructs",
        "key": "data_room",
        "title": "Data Room",
        "icon": "🗄️",
        "primary_user": "technical coauthor or data editor",
        "task": "Locate data products, inspect validation status, and understand private-data boundaries.",
        "inputs": "data product catalog, source manifests, and audit reports",
        "outputs": "coverage, keys, status badges, evidence panels, metadata-only schema checks, and locate-data commands",
        "safety_rule": "Hide private-data-root commands in Demo Mode; never display row-level private values.",
    },
    {
        "group": "Data And Constructs",
        "key": "construct_audits",
        "title": "Construct Audits",
        "icon": "🧭",
        "primary_user": "coauthor or data editor",
        "task": "Open construct playbooks, audit counts, and limitation surfaces.",
        "inputs": "construct playbook registry, data product catalog, and audit reports",
        "outputs": "playbook links, construct-info commands, classifier/patent/WRDS evidence, and risk summaries",
        "safety_rule": "Summarize audit counts only; no private row examples.",
    },
    {
        "group": "Extensions And Reproduction",
        "key": "extension_lab",
        "title": "Extension Lab",
        "icon": "🧪",
        "primary_user": "technical coauthor",
        "task": "Inspect exploratory extension lanes, generated aggregate outputs, and future-data requirements.",
        "inputs": "extension workbench, ignored extension outputs, and SEO/offering-terms schema template",
        "outputs": "extension cards, status badges, output previews, commands, limits, and schema-only checks",
        "safety_rule": "Label extension outputs as not manuscript-ready unless promoted; never display private row-level values.",
    },
    {
        "group": "Extensions And Reproduction",
        "key": "reproduction_status",
        "title": "Reproduction Status",
        "icon": "✅",
        "primary_user": "journal data editor",
        "task": "Verify reproduction and audit posture.",
        "inputs": "status docs and manifests",
        "outputs": "status links and audit commands",
        "safety_rule": "No command execution from the browser.",
    },
    {
        "group": "Extensions And Reproduction",
        "key": "command_center",
        "title": "Command Center",
        "icon": "▶️",
        "primary_user": "trusted local coauthor",
        "task": "Run approved Make targets with confirmation gates and ignored logs.",
        "inputs": "dashboard command registry and local workstation environment",
        "outputs": "exit code, duration, sanitized log tail, and ignored raw log path",
        "safety_rule": "Allowlisted Make targets only; disabled in Demo Mode.",
    },
    {
        "group": "Extensions And Reproduction",
        "key": "share_export",
        "title": "Share / Export Center",
        "icon": "📦",
        "primary_user": "all users",
        "task": "Find export, setup, dashboard, and share-readiness commands.",
        "inputs": "workbench and dashboard commands",
        "outputs": "copy-ready commands and share checklist pointers",
        "safety_rule": "Commands are displayed only.",
    },
]


def specs_by_key() -> dict[str, dict[str, str]]:
    return {spec["key"]: spec for spec in PAGE_SPECS}
